# Invoked through the per-configuration script generated by CMakeLists.txt.
cmake_minimum_required(VERSION 3.21.1)
if(NOT CMAKE_HOST_APPLE)
    message(FATAL_ERROR "macOS application deployment must run on macOS")
endif()
if(NOT IS_ABSOLUTE "${APP_BUNDLE}" OR NOT APP_BUNDLE MATCHES "\\.app$"
        OR NOT EXISTS "${APP_BUNDLE}/Contents/MacOS/Image_Stitcher_Auto")
    message(FATAL_ERROR "APP_BUNDLE must be the absolute path of the installed .app")
endif()
if(NOT EXISTS "${IMAGE_STITCHER_MACDEPLOYQT}")
    message(FATAL_ERROR "macdeployqt is missing from the Qt installation used to build the app")
endif()

set(deploy_search_options "")
foreach(runtime_directory IN LISTS IMAGE_STITCHER_RUNTIME_SEARCH_DIRS)
    list(APPEND deploy_search_options "-libpath=${runtime_directory}")
endforeach()
execute_process(
    COMMAND "${IMAGE_STITCHER_MACDEPLOYQT}" "${APP_BUNDLE}"
        -verbose=2 -always-overwrite -no-codesign
        ${deploy_search_options}
    RESULT_VARIABLE deploy_result
)
if(NOT deploy_result EQUAL 0)
    message(FATAL_ERROR "macdeployqt failed: ${deploy_result}")
endif()

# Deploy remaining third-party dependencies (OpenCV and image codecs) as well
# as Qt plugins. fixup_bundle also verifies that no non-system dylib is left
# outside the bundle; this catches accidental Homebrew/build-tree dependencies.
set(BUNDLEUTILITIES_COPY_FULL_FRAMEWORK_CONTENTS ON)
set(BU_CHMOD_BUNDLE_ITEMS ON)
include(BundleUtilities)
fixup_bundle("${APP_BUNDLE}" "" "${IMAGE_STITCHER_RUNTIME_SEARCH_DIRS}")

# Rewriting install names invalidates existing signatures. Ad-hoc signing is
# for local testing only; public distribution needs Developer ID/notarization.
execute_process(
    COMMAND /usr/bin/codesign --force --deep --sign - "${APP_BUNDLE}"
    RESULT_VARIABLE sign_result
)
if(NOT sign_result EQUAL 0)
    message(FATAL_ERROR "Local ad-hoc signing failed: ${sign_result}")
endif()
execute_process(
    COMMAND /usr/bin/codesign --verify --deep --strict "${APP_BUNDLE}"
    RESULT_VARIABLE verify_result
)
if(NOT verify_result EQUAL 0)
    message(FATAL_ERROR "Bundle signature verification failed: ${verify_result}")
endif()
